.catalog:
  name: Infra
  version: 0.4.0
  description: Trusted SSL certificates at zero cost
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: API_VERSION
      label: Let's Encrypt API Version
      description: |
        Select the API version used for issuing the certificate.
        Use `Sandbox` for testing only.
      required: true
      type: enum
      default: Production
      options:
        - Production
        - Sandbox
    - variable: EMAIL
      label: Your Email Address
      description: |
        Enter the email address to use for creating the Let's Encrypt account.
      required: true
      type: string
    - variable: CERT_NAME
      label: Certificate Name
      description: |
        Name for storing the certificate in the Rancher API and in volumes.
        Any existing certificate by that name will be updated.
      required: true
      type: string
    - variable: DOMAINS
      label: Domain Names
      description: |
        Comma delimited list of the certificate domains for gitlab and registry.
        E.g: `git.example.com, registry.example.com`.
      required: true
      type: string
    - variable: PUBLIC_KEY_TYPE
      label: Public Key Algorithm
      description: |
        Select one of the available key types.
      required: true
      type: enum
      default: RSA-2048
      options:
        - RSA-2048
        - RSA-4096
        - RSA-8192
        - ECDSA-256
        - ECDSA-384
    - variable: RENEWAL_TIME
      label: Renewal Time of Day (00-23)
      description: |
        Set the time of day (UTC in hours) at which certificate renewals should be run.
      default: 12
      required: true
      type: int
    - variable: GITLAB_SECRETS_DB_KEY_BASE
      label: Gitlab secrets db key base
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_SECRETS_SECRET_KEY_BASE
      label: Gitlab secrets db key base
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_SECRETS_OTP_KEY_BASE
      label: Gitlab secrets db key base
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_DB_ADAPTER
      label: Gitlab db adapter
      required: true
      type: string
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_DB_PASS
      label: Gitlab db pass
      required: true
      type: password
    - variable: GITLAB_DB_USER
      label: Gitlab db user
      required: true
      type: string
      default: gitlab
    - variable: GITLAB_HOST
      label: Gitlab host
      required: true
      type: string
    - variable: GITLAB_PORT
      label: Gitlab host
      required: true
      type: string
      default: 80
    - variable: GITLAB_REGISTRY_HOST
      label: Registry host
      required: true
      type: string
    - variable: GITLAB_REGISTRY_HOST
      label: Registry host
      required: true
      type: string
    - variable: GITLAB_REGISTRY_API_URL
      label: Registry api url
      required: true
      type: string
      default: http://registry:5000
    - variable: GITLAB_REGISTRY_ENABLED
      label: Registry enabled
      required: true
      type: string
      default: 'true'
    - variable: GITLAB_REGISTRY_ISSUER
      label: Registry issuer
      required: true
      type: string
      default: gitlab-issuer
    - variable: GITLAB_REGISTRY_ISSUER
      label: Registry issuer
      required: true
      type: string
      default: gitlab-issuer
    - variable: GITLAB_REGISTRY_KEY_PATH
      label: Registry key path
      required: true
      type: string
      default: /certs/production/certs/inkmap/privkey.pem
    - variable: GITLAB_REGISTRY_ISSUER
      label: Registry issuer
      required: true
      type: string
      default: gitlab-issuer
