.catalog:
  name: Infra-ci
  version: 1.0.1
  uuid: infra-1
  description: Trusted SSL certificates at zero cost
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: API_VERSION
      label: Let's Encrypt API Version
      description: |
        Select the API version used for issuing the certificate.
        Use `Sandbox` for testing only.
      required: true
      type: enum
      default: Production
      options:
        - Production
        - Sandbox
    - variable: EMAIL
      label: Your Email Address
      description: |
        Enter the email address to use for creating the Let's Encrypt account.
      required: true
      type: string
    - variable: CERT_NAME
      label: Certificate Name
      description: |
        Name for storing the certificate in the Rancher API and in volumes.
        Any existing certificate by that name will be updated.
      required: true
      type: string
    - variable: GITLAB_HOST
      label: Gitlab subdomain
      required: true
      type: string
    - variable: GITLAB_REGISTRY_HOST
      label: Registry subdomain
      required: true
      type: string
    - variable: DOMAINS
      label: Domain Names
      description: |
        Comma delimited list of the certificate domains starting with the Common Name.
        E.g: `example.com, dev.example.com`.
      required: true
      type: string
    - variable: PUBLIC_KEY_TYPE
      label: Public Key Algorithm
      description: |
        Select one of the available key types.
      required: true
      type: enum
      default: RSA-2048
      options:
        - RSA-2048
        - RSA-4096
        - RSA-8192
        - ECDSA-256
        - ECDSA-384
    - variable: RENEWAL_TIME
      label: Renewal Time of Day (00-23)
      description: |
        Set the time of day (UTC in hours) at which certificate renewals should be run.
      default: 12
      required: true
      type: int
    - variable: GITLAB_SECRETS_DB_KEY_BASE
      label: Gitlab db secret
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_SECRETS_OTP_KEY_BASE
      label: Gitlab otp secret
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_SECRETS_SECRET_KEY_BASE
      label: Gitlab secret
      required: true
      type: password
      default: oib2VIJCUYSnj2BPilrLVsufOuZEK1wb6RmX3jXGs2IkuB8rgOPcyDBQ10rmWEgD
    - variable: GITLAB_DB_PASS
      label: Gitlab db pass
      required: true
      type: password
      default: arandompassword



gitlab-registry-proxy:
  scale: 0
  start_on_create: false
  lb_config:
    certs: []
    config: |-
      frontend 80
        bind *:80
        mode http
        redirect scheme https if !{ ssl_fc }
    default_cert: ${CERT_NAME}
    port_rules:
    - hostname: ${GITLAB_HOST}
      path: /
      priority: 1
      protocol: https
      service: gitlab
      source_port: 443
      target_port: 80
    - hostname:  ${GITLAB_REGISTRY_HOST}
      path: /
      priority: 2
      protocol: https
      service: registry
      source_port: 5000
      target_port: 5000
    - hostname: ${GITLAB_HOST}
      path: /
      priority: 3
      protocol: https
      service: gitlab
      source_port: 5500
      target_port: 5500
    - hostname: ${GITLAB_HOST}
      priority: 4
      protocol: tcp
      service: gitlab
      source_port: 22
      target_port: 22
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
letsencrypt-proxy:
  scale: 1
  start_on_create: false
  lb_config:
    certs: []
    port_rules:
    - hostname: ${GITLAB_HOST}
      path: /.well-known/acme-challenge
      priority: 5
      protocol: http
      service: letsencrypt
      source_port: 80
      target_port: 80
    - hostname: ${GITLAB_REGISTRY_HOST}
      path: /.well-known/acme-challenge
      priority: 6
      protocol: http
      service: letsencrypt
      source_port: 80
      target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
postgresql:
  scale: 1
  start_on_create: true
gl-multi-runner:
  scale: 0
  start_on_create: false
gitlab:
  scale: 1
  start_on_create: true
redis:
  scale: 1
  start_on_create: true
letsencrypt:
  scale: 1
  start_on_create: true
