version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  web:
    image: registry.inkmap.com:5000/devops/ink-api:latest
    command: '/bin/sh docker/init_prod_server.sh'
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    env:
    - POSTGRESQL_HOST: postgres
    - POSTGRESQL_PORT: 6379/1
    - POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    - POSTGRESQL_USERNAME: postgres
    - REDIS_HOST: redis
    - DEVISE_ADMIN_EMAIL: admin@example.com
    - SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    - PRODUCTION_FILE_LOCATION: ./ink_api_files/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  sidekiq:
    image: registry.inkmap.com:5000/devops/ink-api:latest
    command: '/bin/sh docker/init_prod_sidekiq.sh'
    env:
    - POSTGRESQL_HOST: postgres
    - POSTGRESQL_PORT: 6379/1
    - POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    - POSTGRESQL_USERNAME: postgres
    - REDIS_HOST: redis
    - DEVISE_ADMIN_EMAIL: admin@example.com
    - SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    - PRODUCTION_FILE_LOCATION: ./ink_api_files/
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    depends_on:
      - web
      - postgres
