.catalog:
  name: ink-api
  version: 1.0.0
  uuid: ink-api-1
  description: Ink api repo
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: POSTGRESQL_PASSWORD
      label: postgres db pass
      required: true
      type: password
      default: arandompassword
    - variable: SECRET_KEY_BASE
      label: secret key base
      required: true
      type: password
      default: 943d29212a265d6d7781b07f2850dde8b5b1bb72c2b713e2f72c74322d24f06a0da6276c8e88d454c976641fe410d9cc0fc4fd5ad7f2169dbb3593cc117e9d33

version: '2'
services:
  ink-api-proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: api.inkmap.com
        path: /
        priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  web:
    scale: 1
    start_on_create: true
  sidekiq:
    scale: 1
    start_on_create: true
  postgresql:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
