.catalog:
  name: ink-api
  version: 1.0.0
  uuid: ink-api-1
  description: Ink api repo
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: POSTGRESQL_PASSWORD
      label: postgres db pass
      required: true
      type: password
      default: arandompassword
    - variable: SECRET_KEY_BASE
      label: secret key base
      required: true
      type: password
      default: arandompassword


version: '2'
services:
  ink-api-proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: api.inkmap.com
        path: /
        priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  web:
    scale: 1
    start_on_create: true
  sidekiq:
    scale: 1
    start_on_create: true
  postgresql:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
